### PR TITLE
Update to Factor Normalization by Index

### PR DESCRIPTION
**Pull request by thewassermann**
Much faster, does not induce timeout errors when run in backtester

### CODE REVIEW

**Comment by CaptainKanuk** [comment]
There's a merge conflict now with previous changes to the algo. Can you make the changes again but to the new algo and then let me know so we can work through a rebase?

**Comment by thewassermann** [comment]
Sure, sounds good, will investigate

On Tue, Jun 7, 2016 at 3:14 PM, Delaney Granizo-Mackenzie <
notifications@github.com> wrote:

> There's a merge conflict now with previous changes to the algo. Can you
> make the changes again but to the new algo and then let me know so we can
> work through a rebase?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/quantopian/algorithm-component-library/pull/5#issuecomment-224384385,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALaqDaHPrc_r6mFMa_xRj6d_aHtPTO6iks5qJcL9gaJpZM4IM9xX
> .

## 

Gilbert Wassermann
Harvard College '18
A.B. Candidate in Statistics
617-308-6070

**Comment by thewassermann** [comment]
i think the issue is that the pull request was made before freddie added
the .py extension. At the moment it is just plain text. I would drop the
pull request and then I can just do it over, this time adding the .py
extension

On Tue, Jun 7, 2016 at 3:56 PM, Gilbert Wassermann <
wassermann@college.harvard.edu> wrote:

> Sure, sounds good, will investigate
> 
> On Tue, Jun 7, 2016 at 3:14 PM, Delaney Granizo-Mackenzie <
> notifications@github.com> wrote:
> 
> > There's a merge conflict now with previous changes to the algo. Can you
> > make the changes again but to the new algo and then let me know so we can
> > work through a rebase?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/quantopian/algorithm-component-library/pull/5#issuecomment-224384385,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ALaqDaHPrc_r6mFMa_xRj6d_aHtPTO6iks5qJcL9gaJpZM4IM9xX
> > .
> 
> ## 
> 
> Gilbert Wassermann
> Harvard College '18
> A.B. Candidate in Statistics
> 617-308-6070

## 

Gilbert Wassermann
Harvard College '18
A.B. Candidate in Statistics
617-308-6070

**Comment by freddiev4** [comment]
@thewassermann 

`git checkout master`
`git pull`
`git checkout thewassermann-patch-1-faster`
`git rebase master`

Then fix any merge conflicts (and make sure the file contains the `.py` extension)

You should then be able to push a new commit.

cc @CaptainKanuk sound about right?

**Pull request merged**
